# Generated by Django 5.0.6 on 2024-10-16 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_tg_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgMessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('START', 'Старт'), ('RATING', 'Оценивание'), ('COMMENT', 'Комментарий при оценивании'), ('CREATE', 'Создание заявки'), ('LIST', 'Список заявок'), ('DONE', 'Заявка исполнена'), ('TICKET', 'Запрос на создание тикета'), ('ASK_IIN', 'Запрос ИИН'), ('WRONG_CITIZEN', 'Не прошел проверку в БМГ')], max_length=256, verbose_name='Тип сообщения')),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='ID сообщения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История сообщений',
                'verbose_name_plural': 'История сообщений',
            },
        ),
    ]
