# Generated by Django 5.0.6 on 2024-10-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tgmessagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessagehistory',
            name='message_type',
            field=models.CharField(choices=[('START', 'Старт'), ('TICKET', 'Запрос на создание тикета'), ('ASK_CONTRACT_NUMBER', 'Запрос номера договора')], max_length=256, verbose_name='Тип сообщения'),
        ),
    ]
