# Generated by Django 5.0.6 on 2024-10-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
    ]
