# Generated by Django 5.0.6 on 2024-10-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней оплаты'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
