# Generated by Django 5.0.6 on 2024-10-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_last_payment_date_contract_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tech_passport',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
